# Generated by Django 4.2.9 on 2024-02-07 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
