# Generated by Django 5.0.2 on 2024-02-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0003_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='this is a course', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='units',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
