# Generated by Django 5.0.2 on 2024-02-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0004_course_description_course_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='antirequisites',
            field=models.ManyToManyField(to='apiApp.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(to='apiApp.course'),
        ),
    ]
