# Generated by Django 4.2.6 on 2024-03-10 18:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_street_address', models.CharField(max_length=30)),
                ('address_postal_code', models.CharField(max_length=10)),
                ('address_city', models.CharField(max_length=30)),
                ('address_province', models.CharField(max_length=30)),
                ('address_country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('course_title', models.CharField(max_length=60)),
                ('course_description', models.CharField(max_length=300)),
                ('course_prerequisites', models.CharField(blank=True, max_length=50, null=True)),
                ('course_antirequisites', models.CharField(blank=True, max_length=50, null=True)),
                ('course_units', models.IntegerField()),
                ('course_notes', models.CharField(blank=True, max_length=100, null=True)),
                ('course_repeatability', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_contact_name', models.CharField(max_length=30)),
                ('emergency_contact_phone', models.CharField(max_length=15)),
                ('emergency_contact_relationship', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_id', models.CharField(max_length=10)),
                ('instructor_first_name', models.CharField(max_length=30)),
                ('instructor_last_name', models.CharField(max_length=30)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_name', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('program_degree_level', models.CharField(max_length=30)),
                ('program_major', models.CharField(max_length=30)),
                ('program_minor', models.CharField(blank=True, max_length=30, null=True)),
                ('program_honor', models.BooleanField()),
                ('major_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_program', to='api.department')),
                ('minor_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minor_program', to='api.department')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('term_name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('term_year', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('student_first_name', models.CharField(max_length=30)),
                ('student_last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('citizenship_status', models.CharField(max_length=30)),
                ('home_phone_number', models.CharField(blank=True, max_length=15)),
                ('mobile_phone_number', models.CharField(blank=True, max_length=15)),
                ('other_phone_number', models.CharField(blank=True, max_length=15)),
                ('preferred_phone', models.CharField(default='home', max_length=6)),
                ('personal_email', models.EmailField(max_length=254)),
                ('school_email', models.EmailField(max_length=254)),
                ('preferred_email', models.CharField(default='personal', max_length=8)),
                ('preferred_emergency_contact', models.CharField(default='1', max_length=1)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.address')),
                ('emergency_contact1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact1', to='api.emergencycontact')),
                ('emergency_contact2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact2', to='api.emergencycontact')),
                ('emergency_contact3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact3', to='api.emergencycontact')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.program')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_id', models.CharField(max_length=10)),
                ('lecture_days', models.CharField(max_length=10)),
                ('lecture_starttime', models.CharField(max_length=4)),
                ('lecture_endtime', models.CharField(max_length=4)),
                ('lecture_roomnumber', models.CharField(max_length=10)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.instructor')),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.term')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('enrollment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.enrollment')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lecture'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.faculty'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.department'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'lecture')},
        ),
    ]
