# Generated by Django 4.2.6 on 2024-03-06 23:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_name', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('course_title', models.CharField(max_length=60)),
                ('course_number', models.IntegerField()),
                ('course_description', models.CharField(max_length=300)),
                ('course_prerequisites', models.CharField(max_length=50)),
                ('course_antirequisites', models.CharField(max_length=50)),
                ('course_units', models.IntegerField()),
                ('course_notes', models.CharField(max_length=100)),
                ('course_repeatability', models.BooleanField(default=False)),
                ('course_type', models.CharField(max_length=20)),
                ('units', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_id', models.CharField(max_length=10)),
                ('instructor_first_name', models.CharField(max_length=30)),
                ('instructor_last_name', models.CharField(max_length=30)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_name', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('program_year', models.DateField()),
                ('program_load', models.IntegerField()),
                ('program_stream', models.CharField(max_length=30)),
                ('program_major', models.CharField(max_length=30)),
                ('program_minor', models.CharField(max_length=30)),
                ('program_honor', models.BooleanField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('term_name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('student_first_name', models.CharField(max_length=30)),
                ('student_last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(max_length=30)),
                ('citizenship_status', models.CharField(max_length=30)),
                ('street_address', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=30)),
                ('home_phone_number', models.CharField(blank=True, max_length=15)),
                ('mobile_phone_number', models.CharField(blank=True, max_length=15)),
                ('other_phone_number', models.CharField(blank=True, max_length=15)),
                ('preferred_phone', models.CharField(default='home', max_length=6)),
                ('personal_email', models.EmailField(max_length=254)),
                ('school_email', models.EmailField(max_length=254)),
                ('preferred_email', models.CharField(default='personal', max_length=8)),
                ('emergency_contact1_name', models.CharField(max_length=30)),
                ('emergency_contact1_phone', models.CharField(max_length=15)),
                ('emergency_contact1_relationship', models.CharField(max_length=30)),
                ('emergency_contact2_name', models.CharField(blank=True, max_length=30)),
                ('emergency_contact2_phone', models.CharField(blank=True, max_length=15)),
                ('emergency_contact2_relationship', models.CharField(blank=True, max_length=30)),
                ('emergency_contact3_name', models.CharField(blank=True, max_length=30)),
                ('emergency_contact3_phone', models.CharField(blank=True, max_length=15)),
                ('emergency_contact3_relationship', models.CharField(blank=True, max_length=30)),
                ('preferred_emergency_contact', models.CharField(default='1', max_length=1)),
                ('gpa', models.FloatField()),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.department')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.faculty')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.program')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_id', models.CharField(max_length=10)),
                ('lecture_starttime', models.CharField(max_length=4)),
                ('lecture_endtime', models.CharField(max_length=4)),
                ('lecture_roomnumber', models.CharField(max_length=10)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.instructor')),
                ('lecture_term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.term')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('enrollment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.enrollment')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.term'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.faculty'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.faculty'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course', 'term')},
        ),
    ]
