# Generated by Django 4.2.9 on 2024-02-22 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_student_department_student_faculty_student_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='program',
        ),
    ]
