# Generated by Django 4.2.9 on 2024-02-26 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_student_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.program'),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.DateField(),
        ),
    ]
