# Generated by Django 5.0.2 on 2024-02-26 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_student_program_alter_student_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=4)),
                ('course_title', models.CharField(max_length=60)),
                ('course_number', models.IntegerField()),
                ('course_description', models.CharField(max_length=300)),
                ('course_prerequisites', models.CharField(max_length=50)),
                ('course_antirequisites', models.CharField(max_length=50)),
                ('course_units', models.IntegerField()),
                ('course_notes', models.CharField(max_length=100)),
                ('course_repeatability', models.BooleanField(default=False)),
                ('course_type', models.CharField(max_length=20)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_id', models.CharField(max_length=10)),
                ('instructor_fname', models.CharField(max_length=30)),
                ('instructor_lname', models.CharField(max_length=30)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_id', models.CharField(max_length=10)),
                ('lecture_term', models.CharField(max_length=10)),
                ('lecture_starttime', models.CharField(max_length=4)),
                ('lecture_endtime', models.CharField(max_length=4)),
                ('lecture_roomnumber', models.CharField(max_length=10)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student')),
                ('lecture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.lecture')),
            ],
        ),
    ]
